version: '3'

services:
  supla-cloud:
    container_name: ${COMPOSE_PROJECT_NAME}-cloud
    restart: unless-stopped
    image: supla/supla-cloud
    ports:
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
    volumes:
      - ./ssl/cloud:/etc/apache2/ssl:z
      - supla-server-tmp:/supla-server:z
    environment:
      - ADMIN_EMAIL
      - CLOUD_DOMAIN
      - DB_PASSWORD
      - FIRST_USER_EMAIL
      - FIRST_USER_PASSWORD
      - MAILER_ENCRYPTION
      - MAILER_HOST
      - MAILER_PASSWORD
      - MAILER_PORT
      - MAILER_USER
      - RECAPTCHA_ENABLED
      - RECAPTCHA_PRIVATE_KEY
      - RECAPTCHA_PUBLIC_KEY
      - SECRET
    links:
      - supla-db
    depends_on:
      - supla-db

  supla-db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: unless-stopped
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: supla
      MYSQL_USER: supla
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${VOLUME_DATA}/mysql:/var/lib/mysql:z

  supla-server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    restart: unless-stopped
    image: supla/supla-server
    environment:
      - DB_PASSWORD
    volumes:
      - ./ssl/server:/etc/supla-server/ssl:z
      - supla-server-tmp:/tmp:z
    ports:
      - "2016:2016"
      - "2015:2015"
    links:
      - supla-db
    depends_on:
      - supla-cloud

volumes:
  supla-server-tmp: {}
