version: '3'

services:
  supla-cloud:
    container_name: ${COMPOSE_PROJECT_NAME}-cloud
    restart: unless-stopped
    build:
      context: ./cloud
      args:
        CLOUD_VERSION: ${CLOUD_VERSION}
    ports:
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
    volumes:
      - ./cloud/apache-conf:/etc/apache2/sites-available:z
      - ./ssl/cloud:/etc/apache2/ssl:z
      - supla-server-tmp:/supla-server:z
    depends_on:
     - supla-mysql
     - supla-server

  supla-mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: unless-stopped
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: supla
      MYSQL_USER: supla
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
       - ${VOLUME_DATA}/mysql:/var/lib/mysql:z

  supla-server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    restart: unless-stopped
    build:
      context: ./server
      args:
        SERVER_VERSION:
    volumes:
       - ./ssl/server:/etc/supla-server/ssl:z
       - supla-server-tmp:/tmp:z
    ports:
      - 2016:2016
      - 2015:2015
    depends_on:
      - supla-mysql

volumes:
  supla-server-tmp: {}
