supla-cloud:
  container_name: supla-cloud
  image: supla/supla-cloud
  ports:
    - "9999:443"
  environment:
    CLOUD_DOMAIN: cloud.supla.org
    FIRST_USER_EMAIL: user@supla.org
    FIRST_USER_PASSWORD: pass
    DB_PASSWORD: ala123
    SECRET: ala1234
  volumes:
    - ${PWD}/ssl/cloud:/etc/apache2/ssl:z
    - ${PWD}/server:/supla-server:z
  links:
    - supla-db

supla-db:
  container_name: supla-db
  image: mysql:5.7.20
  environment:
    MYSQL_ROOT_PASSWORD: ala123
    MYSQL_DATABASE: supla
    MYSQL_USER: supla
    MYSQL_PASSWORD: ala123
  volumes:
    - ${PWD}/mysql:/var/lib/mysql:z

supla-server:
  container_name: supla-server
  image: supla/supla-server
  environment:
    DB_PASSWORD: ala123
  volumes:
    - ${PWD}/ssl/server:/etc/supla-server/ssl:z
    - ${PWD}/server:/tmp:z
  ports:
    - "2016:2016"
    - "2015:2015"
  links:
    - supla-db
