supla-cloud:
  image: supla/supla-cloud:latest
  ports:
    - "1235:80"
    - "1234:443"
  volumes:
    - /etc/supla-cloud/ssl/cloud:/etc/apache2/ssl:z
    - /etc/supla-cloud/server:/supla-server:z
  environtment:
    DB_PASSWORD: ala123
  links:
    - supla-db

supla-db:
  image: mysql:5.7.20
  environment:
    MYSQL_ROOT_PASSWORD: ala123
    MYSQL_DATABASE: supla
    MYSQL_USER: supla
    MYSQL_PASSWORD: ala123
  volumes:
    - /var/supla/db:/var/lib/mysql:z

supla-server:
  image: supla/supla-server:latest
  environment:
    DB_PASSWORD: ala123
  volumes:
    - /etc/supla-cloud/ssl/server:/etc/apache2/ssl:z
    - /etc/supla-cloud/server:/tmp:z
  ports:
    - "2016:2016"
    - "2015:2015"
  links:
    - supla-db
